// <auto-generated />
using EFCoreEagerLazyExplicitLoading.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreEagerLazyExplicitLoading.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231129064036_intialTable")]
    partial class intialTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreEagerLazyExplicitLoading.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Royal Villa",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Premium Pool Villa",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Luxuary Pool Villa",
                            Price = 400.0
                        });
                });

            modelBuilder.Entity("EFCoreEagerLazyExplicitLoading.Models.VillaAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaAmenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Private Villa 1",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Private Villa 2",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Private Villa 3",
                            VillaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Premium Villa 2",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Premium Villa 3",
                            VillaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Private Luxuary Villa 3",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Premium Luxuary Villa 2",
                            VillaId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Premium Luxuary Villa 3",
                            VillaId = 3
                        });
                });

            modelBuilder.Entity("EFCoreEagerLazyExplicitLoading.Models.VillaAmenity", b =>
                {
                    b.HasOne("EFCoreEagerLazyExplicitLoading.Models.Villa", "Villa")
                        .WithMany("VillaAmenities")
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("EFCoreEagerLazyExplicitLoading.Models.Villa", b =>
                {
                    b.Navigation("VillaAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
