// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Model.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 13, 13, 17, 11, 821, DateTimeKind.Local).AddTicks(4432),
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fstatic%2Fsys-images%2FGuardian%2FPix%2Fpictures%2F2014%2F3%2F21%2F1395401774125%2FLorem-ipsum-011.jpg%3Fwidth%3D465%26dpr%3D1%26s%3Dnone&tbnid=vRZtDL4gTwkgMM&vet=12ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.theguardian.com%2Fbooks%2Fbooksblog%2F2014%2Fmar%2F21%2Florem-ipsum-translated-latin-placeholder-text&docid=Q_SoORA3siVI3M&w=460&h=276&q=lorem%20ipsum&ved=2ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw",
                            IsActive = true,
                            Name = "Pool View",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 13, 13, 17, 11, 821, DateTimeKind.Local).AddTicks(4444),
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fstatic%2Fsys-images%2FGuardian%2FPix%2Fpictures%2F2014%2F3%2F21%2F1395401774125%2FLorem-ipsum-011.jpg%3Fwidth%3D465%26dpr%3D1%26s%3Dnone&tbnid=vRZtDL4gTwkgMM&vet=12ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.theguardian.com%2Fbooks%2Fbooksblog%2F2014%2Fmar%2F21%2Florem-ipsum-translated-latin-placeholder-text&docid=Q_SoORA3siVI3M&w=460&h=276&q=lorem%20ipsum&ved=2ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw",
                            IsActive = true,
                            Name = "Royal View",
                            Occupancy = 15,
                            Rate = 300.0,
                            Sqft = 250,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 13, 13, 17, 11, 821, DateTimeKind.Local).AddTicks(4446),
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fstatic%2Fsys-images%2FGuardian%2FPix%2Fpictures%2F2014%2F3%2F21%2F1395401774125%2FLorem-ipsum-011.jpg%3Fwidth%3D465%26dpr%3D1%26s%3Dnone&tbnid=vRZtDL4gTwkgMM&vet=12ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.theguardian.com%2Fbooks%2Fbooksblog%2F2014%2Fmar%2F21%2Florem-ipsum-translated-latin-placeholder-text&docid=Q_SoORA3siVI3M&w=460&h=276&q=lorem%20ipsum&ved=2ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw",
                            IsActive = true,
                            Name = "Royal View",
                            Occupancy = 15,
                            Rate = 21.0,
                            Sqft = 500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 13, 13, 17, 11, 821, DateTimeKind.Local).AddTicks(4448),
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.guim.co.uk%2Fimg%2Fstatic%2Fsys-images%2FGuardian%2FPix%2Fpictures%2F2014%2F3%2F21%2F1395401774125%2FLorem-ipsum-011.jpg%3Fwidth%3D465%26dpr%3D1%26s%3Dnone&tbnid=vRZtDL4gTwkgMM&vet=12ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw..i&imgrefurl=https%3A%2F%2Fwww.theguardian.com%2Fbooks%2Fbooksblog%2F2014%2Fmar%2F21%2Florem-ipsum-translated-latin-placeholder-text&docid=Q_SoORA3siVI3M&w=460&h=276&q=lorem%20ipsum&ved=2ahUKEwicp9fIusCCAxWToekKHb0QBLkQMygBegQIARBw",
                            IsActive = true,
                            Name = "Royal View",
                            Occupancy = 20,
                            Rate = 150.0,
                            Sqft = 100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
